[tool.poetry]
name = "team-red"
version = "0.1.0"
description = ""
authors = ["cto"]
license = ""
readme = "README.md"

[tool.poetry.scripts]
start = "main:app"

[tool.poetry.dependencies]
python = "^3.9"
ctransformers = "^0.2.24"
faiss-cpu = {version = "~1.7.4", optional = true}
faiss-gpu = {version = "~1.7.2", optional = true}
fastapi = "^0.96.0"
ipykernel = "^6.23.1"
langchain = "0.0.225"
pypdf = "3.8.1"
python-box = "7.0.1"
python-dotenv = "1.0.0"
sentence-transformers = "2.2.2"
uvicorn = "^0.22.0"
torch = ">=2.0.0, !=2.0.1"

[tool.poetry.extras]
cpu = ["faiss-cpu"]
gpu = ["faiss-gpu"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
