[tool.poetry]
name = "team-red"
version = "0.1.0"
description = ""
authors = ["cto"]
license = ""
readme = "README.md"

[tool.poetry.scripts]
start = "main:app"

[tool.poetry.dependencies]
python = "^3.11"
ctransformers = "^0.2.24"
faiss-cpu = {version = "~1.7.4", optional = true}
faiss-gpu = {version = "~1.7.2", optional = true}
fastapi = "^0.96.0"
ipykernel = "^6.23.1"
langchain = "0.0.225"
pypdf = "3.8.1"
python-box = "7.0.1"
python-dotenv = "1.0.0"
sentence-transformers = "2.2.2"
uvicorn = "^0.22.0"
torch = ">=2.0.0, !=2.0.1"
streamlit = "1.25.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pre-commit = "^3.5.0"
ruff = "^0.1.3"

[tool.poetry.extras]
cpu = ["faiss-cpu"]
gpu = ["faiss-gpu"]

[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = [
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "I",     # isort (imports) styling
    "N",     # pep8 naming checks
    "B",     # bugbear checks
    "ANN",   # type annotations
    "S",     # bandid code security
    "C",     # improve code comprehension
    "EM",    # use recommended error message composition
    "G",     # use recommended logging format
    "T20",   # no print allowed
    "PT",    # pytest styling recommendations
    "SLF",   # prevent access to private members
    "SIM",   # code simplification recommendations
    "TCH",   # checks for type checking imports
    "ARG",   # no unused arguments
    "PERF",  # performance anti pattern
    # "FURB",  # enforces modern python
    # "D",     # enforce documented functions [will be enabled soon]

]

# 2. Avoid enforcing line-length violations (`E501`)
# ignore = ["E501"]

# 3. Fix everything except flake8-bugbear (`B`) violations.
fixable = ["ALL"]
unfixable = ["B"]

# 4. Things to ignore
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]  # assert is fine in pytest
# "__init__.py" = ["E402"]
# 
# "**/{tests,docs,tools}/*" = ["E402"]

# [tool.ruff.format]
# # 5. Use single quotes for non-triple-quoted strings.
# quote-style = "single"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
